### PR TITLE
Add extra large font size for headline

### PR DESCRIPTION
**Pull request by tjsilver**
## What does this change?

* Headline now has an 'extra large' option
* Font sizing functionality has been pulled out into a new component for flexibility
* Font sizes have been adjusted to meet provided figures.

## How to test

On local: 
1. Select an image
2. Add some headline text
3. You should now be able to select an 'extra large' font size

### Mobile
image
image
image
image

### Tablet
image
image
image
image

### CODE REVIEW

**Comment by AWare** [comment]
We seem to have lost Guardian Headline Full from this?

**Comment by SHession** [comment]
> We seem to have lost Guardian Headline Full from this?

You're right, we thought we could remove it as it was no longer user but it looks like it is being used in the styling so we will add it back in. Good spot!

**Comment by SHession** [comment]
@AWare I have added those fonts back in.

**Comment by paperboyo** [comment]
Just judging by the screenshots, lineheight between headline and standfirst seems to much smaller for Large option, possibly so tight that ascenders and descenders can clash?

**Pull request merged**
